server:
  port: 8000
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true
      
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/blogProject
    username: root
    password: dlsvlslxM12!
    driverClassName: com.mysql.cj.jdbc.Driver
    
  jpa:
    open-in-view: true
    properties:
      hibernate.hbm2ddl.auto: update
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true

spring.mvc.view.prefix: /WEB-INF/views/
spring.mvc.view.suffix: .jsp
